name: Deploy Streamlit App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check Streamlit installation
        run: |
          streamlit --version
      # Optional: Run your app locally in CI for smoke test (does not keep running)
      # - name: Run Streamlit app for smoke test
      #   run: |
      #     nohup streamlit run index.py &
      #     sleep 30

      # Optional: Add linting or testing steps here

      - name: Complete
        run: echo "✅ Streamlit app CI workflow completed successfully."